### ISSUE TITLE
Links are already connected bug

### ISSUE THREAD

**Issue by Usurfer** [artemsen/pipewalker#11]
Hi, I've installed the Pipewalker game from the Software Manager in Linux mint but when i play the game there is some bug where all the computers/taps are already connected and all i need to do to finish the games is to simply rotate the water source or the start of the link and it finishes the puzzle.

Basically, every computer or tap is basically already linked or connected and it doesn't let you solve anything because everything is link except the water source.

I've tried to install this via the instructions given but I'm having trouble doing that as I am new to this.

**Comment by artemsen** [comment]
It was [fixed](https://github.com/artemsen/pipewalker/commit/72c4cfa37c48a60aebcd537061163ccb3eabc806) in version 1.1, available in Ubuntu 24.10.
