### ISSUE TITLE
Pipewalker depends on SDL 1.2

### ISSUE THREAD

**Issue by davidpolverari** [artemsen/pipewalker#6]
Pipewalker depends on SDL version 1.2, which is unmaintained upstream. Some Linux distributions, such as Debian, will likely drop support for SDL 1.2 in the near future[^1].

If possible, please consider porting it to SDL 2. There is a migration guide written by the SDL maintainers about the process[^2]. As the package maintainer for pipewalker in Debian, I will test it against `libsdl1.2-compat-shim` anyway, to check if it would work on SDL 2 through this shim.

[^1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038538
[^2]: https://wiki.libsdl.org/SDL2/MigrationGuide

**Comment by yselkowitz** [comment]
FYI both Fedora and Flathub build this with sdl12-compat.

**Comment by davidpolverari** [comment]
Hi, @yselkowitz! Thanks a lot for the heads up! This is good news, especially if migration to SDL 2 isn't feasible. I will try to test it on Debian asap and hope to report the same to the Debian SDL packages maintainers.

**Comment by suve** [comment]
I've ported a game from SDL1 to SDL2 before, so I can take a look at this. No promises regarding the timeline, though.

**Comment by suve** [comment]
@artemsen What's the status of the `next` branch, though? Commit 852b64bad2acf30c11670a82cb7abe18c5fb3667 on said branch seems to include porting the game to SDL2.

**Comment by artemsen** [comment]
> status of the next branch

It was a failed attempt at code refactoring.
I was done with the game logic, but UI and SDL made me give up.

> so I can take a look at this

I'd appreciate it!
But I am not sure it is possible without refactoring the project's architecture.
