### ISSUE TITLE
Feature requests: remove unneeded tiles

### ISSUE THREAD

**Issue by toralf** [artemsen/pipewalker#8]
As seen in the screen shot, there are 2 tiles left over, which are not mandatory.

![image](https://github.com/artemsen/pipewalker/assets/1780404/1d42d5b8-96b4-4fcd-87cc-f59f3fed2104)

**Comment by artemsen** [comment]
All levels in the game are auto-generated.
Actually, the game's level number (286 in your screenshot) is a random seed for the path searching algorithm.
So, I can't remove these tiles. Your solution is better than algorithm's one, congratulations! =)
